<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rainie Xie">
<meta name="dcterms.date" content="2024-05-29">

<title>Rainie website - Multinomial logit (MNL) models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Rainie website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../homeworks.html"> 
<span class="menu-text">Homeworks</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estimating-yogurt-preferences" id="toc-estimating-yogurt-preferences" class="nav-link active" data-scroll-target="#estimating-yogurt-preferences">1. Estimating Yogurt Preferences</a>
  <ul class="collapse">
  <li><a href="#likelihood-for-the-multi-nomial-logit-mnl-model" id="toc-likelihood-for-the-multi-nomial-logit-mnl-model" class="nav-link" data-scroll-target="#likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</a></li>
  <li><a href="#yogurt-dataset" id="toc-yogurt-dataset" class="nav-link" data-scroll-target="#yogurt-dataset">Yogurt Dataset</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  <li><a href="#estimating-minivan-preferences" id="toc-estimating-minivan-preferences" class="nav-link" data-scroll-target="#estimating-minivan-preferences">2. Estimating Minivan Preferences</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multinomial logit (MNL) models</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rainie Xie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 29, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This assignment uses the Multinomial logit (MNL) model to analyze (1) yogurt purchase data made by consumers at a retail location, and (2) conjoint data about consumer preferences for minivans.</p>
<section id="estimating-yogurt-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-yogurt-preferences">1. Estimating Yogurt Preferences</h2>
<section id="likelihood-for-the-multi-nomial-logit-mnl-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</h3>
<p>Suppose we have <span class="math inline">\(i=1,\ldots,n\)</span> consumers who each select exactly one product <span class="math inline">\(j\)</span> from a set of <span class="math inline">\(J\)</span> products. The outcome variable is the identity of the product chosen <span class="math inline">\(y_i \in \{1, \ldots, J\}\)</span> or equivalently a vector of <span class="math inline">\(J-1\)</span> zeros and <span class="math inline">\(1\)</span> one, where the <span class="math inline">\(1\)</span> indicates the selected product. For example, if the third product was chosen out of 4 products, then either <span class="math inline">\(y=3\)</span> or <span class="math inline">\(y=(0,0,1,0)\)</span> depending on how we want to represent it. Suppose also that we have a vector of data on each product <span class="math inline">\(x_j\)</span> (eg, size, price, etc.).</p>
<p>We model the consumer’s decision as the selection of the product that provides the most utility, and we’ll specify the utility function as a linear function of the product characteristics:</p>
<p><span class="math display">\[ U_{ij} = x_j'\beta + \epsilon_{ij} \]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an i.i.d. extreme value error term.</p>
<p>The choice of the i.i.d. extreme value error term leads to a closed-form expression for the probability that consumer <span class="math inline">\(i\)</span> chooses product <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[ \mathbb{P}_i(j) = \frac{e^{x_j'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>For example, if there are 4 products, the probability that consumer <span class="math inline">\(i\)</span> chooses product 3 is:</p>
<p><span class="math display">\[ \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{e^{x_1'\beta} + e^{x_2'\beta} + e^{x_3'\beta} + e^{x_4'\beta}} \]</span></p>
<p>A clever way to write the individual likelihood function for consumer <span class="math inline">\(i\)</span> is the product of the <span class="math inline">\(J\)</span> probabilities, each raised to the power of an indicator variable (<span class="math inline">\(\delta_{ij}\)</span>) that indicates the chosen product:</p>
<p><span class="math display">\[ L_i(\beta) = \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} = \mathbb{P}_i(1)^{\delta_{i1}} \times \ldots \times \mathbb{P}_i(J)^{\delta_{iJ}}\]</span></p>
<p>Notice that if the consumer selected product <span class="math inline">\(j=3\)</span>, then <span class="math inline">\(\delta_{i3}=1\)</span> while <span class="math inline">\(\delta_{i1}=\delta_{i2}=\delta_{i4}=0\)</span> and the likelihood is:</p>
<p><span class="math display">\[ L_i(\beta) = \mathbb{P}_i(1)^0 \times \mathbb{P}_i(2)^0 \times \mathbb{P}_i(3)^1 \times \mathbb{P}_i(4)^0 = \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>The joint likelihood (across all consumers) is the product of the <span class="math inline">\(n\)</span> individual likelihoods:</p>
<p><span class="math display">\[ L_n(\beta) = \prod_{i=1}^n L_i(\beta) = \prod_{i=1}^n \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} \]</span></p>
<p>And the joint log-likelihood function is:</p>
<p><span class="math display">\[ \ell_n(\beta) = \sum_{i=1}^n \sum_{j=1}^J \delta_{ij} \log(\mathbb{P}_i(j)) \]</span></p>
</section>
<section id="yogurt-dataset" class="level3">
<h3 class="anchored" data-anchor-id="yogurt-dataset">Yogurt Dataset</h3>
<p>We will use the <code>yogurt_data</code> dataset, which provides anonymized consumer identifiers (<code>id</code>), a vector indicating the chosen product (<code>y1</code>:<code>y4</code>), a vector indicating if any products were “featured” in the store as a form of advertising (<code>f1</code>:<code>f4</code>), and the products’ prices (<code>p1</code>:<code>p4</code>). For example, consumer 1 purchased yogurt 4 at a price of 0.079/oz and none of the yogurts were featured/advertised at the time of consumer 1’s purchase. Consumers 2 through 7 each bought yogurt 2, etc.</p>
<section id="dataset" class="level4">
<h4 class="anchored" data-anchor-id="dataset">Dataset</h4>
<div id="6b9989ec" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the data and show the first few rows</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>yogurt <span class="op">=</span> pd.read_csv(<span class="st">'./yogurt_data.csv'</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yogurt.head()) </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yogurt.describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id  y1  y2  y3  y4  f1  f2  f3  f4     p1     p2     p3     p4
0   1   0   0   0   1   0   0   0   0  0.108  0.081  0.061  0.079
1   2   0   1   0   0   0   0   0   0  0.108  0.098  0.064  0.075
2   3   0   1   0   0   0   0   0   0  0.108  0.098  0.061  0.086
3   4   0   1   0   0   0   0   0   0  0.108  0.098  0.061  0.086
4   5   0   1   0   0   0   0   0   0  0.125  0.098  0.049  0.079
              id           y1           y2           y3           y4  \
count  2430.0000  2430.000000  2430.000000  2430.000000  2430.000000   
mean   1215.5000     0.341975     0.401235     0.029218     0.227572   
std     701.6249     0.474469     0.490249     0.168452     0.419351   
min       1.0000     0.000000     0.000000     0.000000     0.000000   
25%     608.2500     0.000000     0.000000     0.000000     0.000000   
50%    1215.5000     0.000000     0.000000     0.000000     0.000000   
75%    1822.7500     1.000000     1.000000     0.000000     0.000000   
max    2430.0000     1.000000     1.000000     1.000000     1.000000   

                f1           f2           f3           f4           p1  \
count  2430.000000  2430.000000  2430.000000  2430.000000  2430.000000   
mean      0.055556     0.039506     0.037449     0.037449     0.106248   
std       0.229109     0.194836     0.189897     0.189897     0.020587   
min       0.000000     0.000000     0.000000     0.000000    -0.012000   
25%       0.000000     0.000000     0.000000     0.000000     0.103000   
50%       0.000000     0.000000     0.000000     0.000000     0.108000   
75%       0.000000     0.000000     0.000000     0.000000     0.115000   
max       1.000000     1.000000     1.000000     1.000000     0.193000   

                p2           p3           p4  
count  2430.000000  2430.000000  2430.000000  
mean      0.081532     0.053622     0.079507  
std       0.011047     0.008054     0.007714  
min       0.000000     0.025000     0.004000  
25%       0.081000     0.050000     0.079000  
50%       0.086000     0.054000     0.079000  
75%       0.086000     0.061000     0.086000  
max       0.111000     0.086000     0.104000  </code></pre>
</div>
</div>
</section>
<section id="visualizing" class="level4">
<h4 class="anchored" data-anchor-id="visualizing">Visualizing</h4>
<div id="d5d4a72d" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>price_columns <span class="op">=</span> [<span class="st">'p1'</span>, <span class="st">'p2'</span>, <span class="st">'p3'</span>, <span class="st">'p4'</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms for prices of each product</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Price Distributions for Each Product'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(yogurt[<span class="st">'p1'</span>], bins<span class="op">=</span><span class="dv">20</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">0</span>])</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'Product 1'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>sns.histplot(yogurt[<span class="st">'p2'</span>], bins<span class="op">=</span><span class="dv">20</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">'Product 2'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>sns.histplot(yogurt[<span class="st">'p3'</span>], bins<span class="op">=</span><span class="dv">20</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">0</span>])</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'Product 3'</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>sns.histplot(yogurt[<span class="st">'p4'</span>], bins<span class="op">=</span><span class="dv">20</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'Product 4'</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot boxplots for prices of each product</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>yogurt[price_columns])</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Boxplot of Prices for Each Product'</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-3-output-1.png" width="1141" height="755" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-3-output-2.png" width="802" height="505" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Based on the plots, we can see that:</p>
<ul>
<li><strong>Consistency</strong>: Product 1 has the most consistent pricing, with prices mostly around $0.125.</li>
<li><strong>Low Price Strategy</strong>: Product 3 generally has the lowest prices but shows more variability, possibly indicating different pricing tiers or promotional strategies.</li>
<li><strong>Middle Ground</strong>: Products 2 and 4 have similar pricing strategies, both centered around $0.08, suggesting they might be positioned similarly in the market.</li>
<li><strong>Outliers</strong>: The presence of lower-priced outliers across all products could indicate promotional pricing or discounts. Product 1 also has a higher outlier, suggesting occasional premium pricing.”</li>
</ul>
</section>
<section id="data-preparation" class="level4">
<h4 class="anchored" data-anchor-id="data-preparation">Data Preparation</h4>
<p>Now, let the vector of product features include brand dummy variables for yogurts 1-3 (we’ll omit a dummy for product 4 to avoid multi-collinearity), a dummy variable to indicate if a yogurt was featured, and a continuous variable for the yogurts’ prices:</p>
<p><span class="math display">\[ x_j' = [\mathbbm{1}(\text{Yogurt 1}), \mathbbm{1}(\text{Yogurt 2}), \mathbbm{1}(\text{Yogurt 3}), X_f, X_p] \]</span></p>
<p>The “hard part” of the MNL likelihood function is organizing the data, as we need to keep track of 3 dimensions (consumer <span class="math inline">\(i\)</span>, covariate <span class="math inline">\(k\)</span>, and product <span class="math inline">\(j\)</span>) instead of the typical 2 dimensions for cross-sectional regression models (consumer <span class="math inline">\(i\)</span> and covariate <span class="math inline">\(k\)</span>).</p>
<p>What we would like to do is reorganize the data from a “wide” shape with <span class="math inline">\(n\)</span> rows and multiple columns for each covariate, to a “long” shape with <span class="math inline">\(n \times J\)</span> rows and a single column for each covariate. As part of this re-organization, we’ll add binary variables to indicate the first 3 products; the variables for featured and price are included in the dataset and simply need to be “pivoted” or “melted” from wide to long.</p>
<div id="1f571307" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt the product choices, feature status, and prices in one step</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>long_yogurt <span class="op">=</span> pd.wide_to_long(yogurt, stubnames<span class="op">=</span>[<span class="st">'y'</span>, <span class="st">'f'</span>, <span class="st">'p'</span>], i<span class="op">=</span><span class="st">'id'</span>, j<span class="op">=</span><span class="st">'product'</span>, sep<span class="op">=</span><span class="st">''</span>, suffix<span class="op">=</span><span class="st">'</span><span class="ch">\\</span><span class="st">d+'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset index to get a tidy dataframe</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>long_yogurt <span class="op">=</span> long_yogurt.reset_index()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns to match the desired format</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>long_yogurt <span class="op">=</span> long_yogurt.rename(columns<span class="op">=</span>{<span class="st">'y'</span>: <span class="st">'choice'</span>, <span class="st">'f'</span>: <span class="st">'featured'</span>, <span class="st">'p'</span>: <span class="st">'price'</span>})</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for the first three products</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>long_yogurt[<span class="st">'yogurt_1'</span>] <span class="op">=</span> (long_yogurt[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">1</span>).astype(<span class="bu">int</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>long_yogurt[<span class="st">'yogurt_2'</span>] <span class="op">=</span> (long_yogurt[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">2</span>).astype(<span class="bu">int</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>long_yogurt[<span class="st">'yogurt_3'</span>] <span class="op">=</span> (long_yogurt[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by 'id'</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>long_yogurt <span class="op">=</span> long_yogurt.sort_values(by<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product'</span>]).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop 'product' column </span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>long_yogurt <span class="op">=</span> long_yogurt.drop(columns<span class="op">=</span>[<span class="st">'product'</span>])</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>long_yogurt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">choice</th>
<th data-quarto-table-cell-role="th">featured</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">yogurt_1</th>
<th data-quarto-table-cell-role="th">yogurt_2</th>
<th data-quarto-table-cell-role="th">yogurt_3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.081</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.061</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0.079</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9715</td>
<td>2429</td>
<td>1</td>
<td>0</td>
<td>0.086</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9716</td>
<td>2430</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9717</td>
<td>2430</td>
<td>0</td>
<td>0</td>
<td>0.086</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9718</td>
<td>2430</td>
<td>0</td>
<td>0</td>
<td>0.043</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9719</td>
<td>2430</td>
<td>1</td>
<td>0</td>
<td>0.079</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>9720 rows × 7 columns</p>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<section id="define-the-log-likelihood-function" class="level4">
<h4 class="anchored" data-anchor-id="define-the-log-likelihood-function">Define the log-likelihood function</h4>
<div id="c31a3a84" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the log-likelihood function</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(beta, X, y):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    Xbeta <span class="op">=</span> np.dot(X, beta)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    exp_Xbeta <span class="op">=</span> np.exp(Xbeta)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(y <span class="op">*</span> Xbeta <span class="op">-</span> np.log(<span class="dv">1</span> <span class="op">+</span> exp_Xbeta))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the function to calculate the gradient</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gradient(beta, X, y):</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    Xbeta <span class="op">=</span> np.dot(X, beta)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    exp_Xbeta <span class="op">=</span> np.exp(Xbeta)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    prob <span class="op">=</span> exp_Xbeta <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> exp_Xbeta)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    gradient <span class="op">=</span> np.dot(X.T, y <span class="op">-</span> prob)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>gradient</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="optimize-the-log-likelihood-function" class="level4">
<h4 class="anchored" data-anchor-id="optimize-the-log-likelihood-function">Optimize the log-likelihood function</h4>
<div id="24b513bd" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the variables</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> long_yogurt[[<span class="st">'yogurt_1'</span>, <span class="st">'yogurt_2'</span>, <span class="st">'yogurt_3'</span>,<span class="st">'featured'</span>, <span class="st">'price'</span>]].values</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> long_yogurt[<span class="st">'choice'</span>].values</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure the dependent variable is binary</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> (y <span class="op">==</span> <span class="dv">1</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add intercept</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.hstack((np.ones((X.shape[<span class="dv">0</span>], <span class="dv">1</span>)), X))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize beta</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>])</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize the log-likelihood function</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(log_likelihood, initial_beta, args<span class="op">=</span>(X, y), jac<span class="op">=</span>gradient, method<span class="op">=</span><span class="st">'BFGS'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result.x</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>beta_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>array([  1.28298667,   1.41787094,   0.90126398,  -3.14053695,
         0.47140946, -31.97609653])</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Use MNlogit package to verify the results
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="9cbffc5a" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the feature columns into a single matrix X</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>X_mn <span class="op">=</span> long_yogurt[[<span class="st">'yogurt_1'</span>, <span class="st">'yogurt_2'</span>, <span class="st">'yogurt_3'</span>, <span class="st">'featured'</span>, <span class="st">'price'</span>]]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The dependent variable is the product choice</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>y_mn <span class="op">=</span> long_yogurt[<span class="st">'choice'</span>]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the multinomial logit model using statsmodels</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>X_mn <span class="op">=</span> sm.add_constant(X_mn)  <span class="co"># Add a constant term to the predictors</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.MNLogit(y_mn, X_mn)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>result_mn <span class="op">=</span> model.fit()</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary of the model</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>result_mn.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.477971
         Iterations 7</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>MNLogit Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>choice</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>9720</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>MNLogit</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>9714</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>MLE</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 29 May 2024</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ.:</td>
<td>0.1500</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>15:00:22</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-4645.9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">converged:</td>
<td>True</td>
<td data-quarto-table-cell-role="th">LL-Null:</td>
<td>-5465.9</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th">LLR p-value:</td>
<td>0.000</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">choice=1</td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>1.2830</td>
<td>0.173</td>
<td>7.420</td>
<td>0.000</td>
<td>0.944</td>
<td>1.622</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">yogurt_1</td>
<td>1.4179</td>
<td>0.089</td>
<td>16.008</td>
<td>0.000</td>
<td>1.244</td>
<td>1.591</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">yogurt_2</td>
<td>0.9013</td>
<td>0.065</td>
<td>13.909</td>
<td>0.000</td>
<td>0.774</td>
<td>1.028</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">yogurt_3</td>
<td>-3.1405</td>
<td>0.142</td>
<td>-22.072</td>
<td>0.000</td>
<td>-3.419</td>
<td>-2.862</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">featured</td>
<td>0.4714</td>
<td>0.119</td>
<td>3.959</td>
<td>0.000</td>
<td>0.238</td>
<td>0.705</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">price</td>
<td>-31.9761</td>
<td>2.089</td>
<td>-15.305</td>
<td>0.000</td>
<td>-36.071</td>
<td>-27.881</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Result from manual calculation and MNlogit package calculation is the same.</p>
</div>
</div>
</div>
</section>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>We learn…</p>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation">Interpretation:</h4>
<ol type="1">
<li><p><strong>Intercept (const): 1.2830</strong></p>
<ul>
<li>The intercept represents the baseline log-odds of choosing a product when all predictor variables are zero. This is the reference level.</li>
</ul></li>
<li><p><strong>Yogurt Type Coefficients:</strong></p>
<ul>
<li><strong>yogurt_1 (1.4179):</strong>
<ul>
<li>This positive coefficient indicates that yogurt brand 1 has a higher preference compared to the baseline (yogurt 4).</li>
<li>The exponentiated coefficient, <code>exp(1.4179) ≈ 4.13</code>, indicates that the odds of choosing yogurt brand 1 are about 4.13 times higher than the baseline choice.</li>
</ul></li>
<li><strong>yogurt_2 (0.9013):</strong>
<ul>
<li>This positive coefficient indicates that yogurt brand 2 also has a higher preference compared to the yogurt 4.</li>
<li>The exponentiated coefficient, <code>exp(0.9013) ≈ 2.46</code>, indicates that the odds of choosing yogurt brand 2 are about 2.46 times higher than the baseline choice.</li>
</ul></li>
<li><strong>yogurt_3 (-3.1405):</strong>
<ul>
<li>This negative coefficient indicates that yogurt brand 3 is less preferred compared to the yogurt 4.</li>
<li>The exponentiated coefficient, <code>exp(-3.1405) ≈ 0.04</code>, indicates that the odds of choosing yogurt brand 3 are about 0.04 times (or 96% less) than the baseline choice.</li>
</ul></li>
</ul></li>
<li><p><strong>Price (-31.9761):</strong></p>
<ul>
<li>This large negative coefficient indicates that as the price of the yogurt increases, the likelihood of choosing that yogurt decreases significantly.</li>
<li>The exponentiated coefficient, <code>exp(-31.9761) ≈ 0</code>, shows a very strong aversion to higher prices.</li>
</ul></li>
<li><p><strong>Featured (0.4714):</strong></p>
<ul>
<li>This positive coefficient indicates that if a yogurt is featured, it has a higher preference compared to a non-featured yogurt.</li>
<li>The exponentiated coefficient, <code>exp(0.4714) ≈ 1.60</code>, indicates that the odds of choosing a featured yogurt are about 1.60 times higher than a non-featured yogurt.</li>
</ul></li>
</ol>
</section>
<section id="dollar-benefit-calculation" class="level4">
<h4 class="anchored" data-anchor-id="dollar-benefit-calculation">Dollar Benefit Calculation</h4>
<p>Next, use the estimated price coefficient as a dollar-per-util conversion factor to calculate the dollar benefit between the most-preferred yogurt and the least preferred yogurt.</p>
<ol type="1">
<li><strong>Identify the coefficients for the most-preferred and least-preferred yogurts:</strong>
<ul>
<li>Most-preferred yogurt: Yogurt 1 (coefficient = 1.4179)</li>
<li>Least-preferred yogurt: Yogurt 3 (coefficient = -3.1405)</li>
</ul></li>
<li><strong>Calculate the difference in utility:</strong>
<ul>
<li>Utility difference = Coefficient of Yogurt 1 - Coefficient of Yogurt 3</li>
</ul></li>
<li><strong>Convert this utility difference to a dollar value using the price coefficient:</strong>
<ul>
<li>Price coefficient (as dollar-per-util conversion factor): -31.9761</li>
</ul></li>
<li><strong>Utility difference:</strong></li>
</ol>
<p><span class="math display">\[
\text{Utility difference} = 1.4179 - (-3.1405) = 1.4179 + 3.1405 = 4.5584
\]</span></p>
<ol start="2" type="1">
<li><strong>Dollar benefit:</strong></li>
</ol>
<p><span class="math display">\[
\text{Dollar benefit} = \frac{\text{Utility difference}}{|\text{Price coefficient}|} = \frac{4.5584}{31.9761} \approx 0.1426
\]</span></p>
<p>So, the dollar benefit between the most-preferred yogurt (Yogurt 1) and the least-preferred yogurt (Yogurt 3) is approximately $0.1426 per unit. This means that consumers value Yogurt 1 about $0.1426 more per unit than Yogurt 3.</p>
</section>
<section id="simulate-counterfactual" class="level4">
<h4 class="anchored" data-anchor-id="simulate-counterfactual">Simulate Counterfactual</h4>
<p>One benefit of the MNL model is that we can simulate counterfactuals (eg, what if the price of yogurt 1 was $0.10/oz instead of $0.08/oz).</p>
<div id="c9342503" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict choice probabilities</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>predicted_probs <span class="op">=</span> result_mn.predict(X_mn)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate current market shares</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>current_market_shares <span class="op">=</span> predicted_probs.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Current Market Shares:"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(current_market_shares)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Increase the price of yogurt 1 by $0.10</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>X_mn_new <span class="op">=</span> X_mn.copy()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>X_mn_new.loc[long_yogurt[<span class="st">'yogurt_1'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'price'</span>] <span class="op">+=</span> <span class="fl">0.10</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict new choice probabilities with increased price for yogurt 1</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>predicted_probs_new <span class="op">=</span> result_mn.predict(X_mn_new)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate new market shares</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>new_market_shares <span class="op">=</span> predicted_probs_new.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"New Market Shares after $0.10 price increase for Yogurt 1:"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(new_market_shares)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if the market share of yogurt 1 decreased</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>market_share_decrease <span class="op">=</span> current_market_shares[<span class="dv">1</span>] <span class="op">-</span> new_market_shares[<span class="dv">1</span>]</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Change in Market Share for Yogurt 1:"</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(market_share_decrease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Current Market Shares:
0    0.75
1    0.25
dtype: float64
New Market Shares after $0.10 price increase for Yogurt 1:
0    0.828349
1    0.171651
dtype: float64
Change in Market Share for Yogurt 1:
0.07834917598912244</code></pre>
</div>
</div>
<p>The market share for yogurt 1 decreased by 0.0784 after the price increase. This indicates that the price sensitivity for yogurt 1 is significant, and consumers are likely to switch to other options when its price increases.</p>
</section>
</section>
</section>
<section id="estimating-minivan-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-minivan-preferences">2. Estimating Minivan Preferences</h2>
<p>Now let’s perform a conjoint analysis to estimate consumer preferences for different minivan attributes using a Multinomial Logit (MNL) model. The data consists of responses from a conjoint survey where respondents were presented with various minivan configurations and asked to choose their preferred option. The attributes considered in the analysis include the number of seats, cargo space, engine type, and price.</p>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div id="918399a4" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>minivan_data <span class="op">=</span> pd.read_csv(<span class="st">'./rintro-chapter13conjoint.csv'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(minivan_data.describe()) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of unique respondents</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>num_respondents <span class="op">=</span> minivan_data[<span class="st">'resp.id'</span>].nunique()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Average number of choice tasks per respondent</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>avg_choice_tasks_per_respondent <span class="op">=</span> minivan_data.groupby(<span class="st">'resp.id'</span>)[<span class="st">'ques'</span>].nunique().mean()</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of alternatives per choice task</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>alternatives_per_choice_task <span class="op">=</span> minivan_data.groupby([<span class="st">'resp.id'</span>, <span class="st">'ques'</span>])[<span class="st">'alt'</span>].nunique().mean()</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>num_respondents, avg_choice_tasks_per_respondent, alternatives_per_choice_task</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           resp.id         ques          alt         seat        price  \
count  9000.000000  9000.000000  9000.000000  9000.000000  9000.000000   
mean    100.500000     8.000000     2.000000     6.995444    35.003889   
std      57.737513     4.320734     0.816542     0.817005     4.083728   
min       1.000000     1.000000     1.000000     6.000000    30.000000   
25%      50.750000     4.000000     1.000000     6.000000    30.000000   
50%     100.500000     8.000000     2.000000     7.000000    35.000000   
75%     150.250000    12.000000     3.000000     8.000000    40.000000   
max     200.000000    15.000000     3.000000     8.000000    40.000000   

            choice  
count  9000.000000  
mean      0.333333  
std       0.471431  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>(200, 15.0, 3.0)</code></pre>
</div>
</div>
<ul>
<li><strong>Number of Respondents</strong>: 200</li>
<li><strong>Number of Choice Tasks per Respondent</strong>: 15</li>
<li><strong>Number of Alternatives per Choice Task</strong>: 3</li>
</ul>
<section id="attributes-and-levels" class="level5">
<h5 class="anchored" data-anchor-id="attributes-and-levels">Attributes and Levels:</h5>
<ul>
<li><strong>Number of seats</strong>: 6, 7, 8</li>
<li><strong>Cargo space</strong>: 2ft, 3ft</li>
<li><strong>Engine type</strong>: Gas, Hybrid, Electric</li>
<li><strong>Price</strong>: Various values in thousands of dollars</li>
</ul>
</section>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<p>Now, estimate a MNL model omitting the following levels to avoide multicollinearity (6 seats, 2ft cargo, and gas engine). Include price as a continuous variable.</p>
<div id="87a5bf00" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert 'carpool' to binary (0 or 1)</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>minivan_data[<span class="st">'carpool'</span>] <span class="op">=</span> minivan_data[<span class="st">'carpool'</span>].<span class="bu">map</span>({<span class="st">'yes'</span>: <span class="dv">1</span>, <span class="st">'no'</span>: <span class="dv">0</span>})</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert categorical variables to dummy variables</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>minivan_dummies <span class="op">=</span> pd.get_dummies(minivan_data, columns<span class="op">=</span>[<span class="st">'seat'</span>, <span class="st">'cargo'</span>, <span class="st">'eng'</span>]).astype(<span class="bu">int</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Omit seat_6, cargo_2ft, and eng_gas as the reference categories</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>independent_vars <span class="op">=</span> [</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seat_7'</span>, <span class="st">'seat_8'</span>,   <span class="co"># Seat: 6 is omitted</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'cargo_3ft'</span>,          <span class="co"># Cargo space: 2ft is omitted</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'eng_hyb'</span>, <span class="st">'eng_elec'</span>,<span class="co"># Engine type: gas is omitted</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'price'</span>               <span class="co"># Price as a continuous variable</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a constant to the independent variables</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(minivan_dummies[independent_vars])</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> minivan_dummies[<span class="st">'choice'</span>]</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the MNL model</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.MNLogit(y, X)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> model.fit()</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>result.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.558663
         Iterations 6</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>MNLogit Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>choice</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>9000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>MNLogit</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>8993</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>MLE</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 29 May 2024</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ.:</td>
<td>0.1223</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>15:00:23</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5028.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">converged:</td>
<td>True</td>
<td data-quarto-table-cell-role="th">LL-Null:</td>
<td>-5728.6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th">LLR p-value:</td>
<td>1.252e-299</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">choice=1</td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>5.5322</td>
<td>0.224</td>
<td>24.677</td>
<td>0.000</td>
<td>5.093</td>
<td>5.972</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">seat_7</td>
<td>-0.5248</td>
<td>0.060</td>
<td>-8.800</td>
<td>0.000</td>
<td>-0.642</td>
<td>-0.408</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">seat_8</td>
<td>-0.2931</td>
<td>0.059</td>
<td>-5.009</td>
<td>0.000</td>
<td>-0.408</td>
<td>-0.178</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">cargo_3ft</td>
<td>0.4385</td>
<td>0.049</td>
<td>9.004</td>
<td>0.000</td>
<td>0.343</td>
<td>0.534</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">eng_hyb</td>
<td>-0.7605</td>
<td>0.057</td>
<td>-13.361</td>
<td>0.000</td>
<td>-0.872</td>
<td>-0.649</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">eng_elec</td>
<td>-1.4347</td>
<td>0.062</td>
<td>-23.217</td>
<td>0.000</td>
<td>-1.556</td>
<td>-1.314</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">price</td>
<td>-0.1591</td>
<td>0.006</td>
<td>-25.616</td>
<td>0.000</td>
<td>-0.171</td>
<td>-0.147</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1">Interpretation:</h4>
<ol type="1">
<li><strong>Constant (const)</strong>: The baseline utility for choosing an alternative.</li>
<li><strong>Number of Seats</strong>:
<ul>
<li><strong>seat_7 (-0.5248)</strong>: Negative coefficient indicates that 7-seat options are less preferred compared to the omitted 6-seat option.</li>
<li><strong>seat_8 (-0.2931)</strong>: Negative coefficient indicates that 8-seat options are also less preferred compared to the 6-seat option but to a lesser extent than 7-seat options.</li>
</ul></li>
<li><strong>Cargo Space (cargo_3ft, 0.4385)</strong>: Positive coefficient indicates that a 3ft cargo space is more preferred compared to the omitted 2ft option. This suggests respondents value more cargo space.</li>
<li><strong>Engine Type</strong>:
<ul>
<li><strong>eng_hyb (-0.7605)</strong>: Negative coefficient indicates that hybrid engines are less preferred compared to the omitted gas engine.</li>
<li><strong>eng_elec (-1.4347)</strong>: Negative coefficient indicates that electric engines are even less preferred compared to the gas engine. This is the most strongly negative coefficient, suggesting a significant preference against electric engines.</li>
</ul></li>
<li><strong>Price (price, -0.1591)</strong>: Negative coefficient indicates that higher prices reduce the likelihood of an alternative being chosen. This is expected, as higher costs generally deter consumers.</li>
</ol>
<ul>
<li><p><strong>Preferred Features</strong>:</p>
<ul>
<li>More Cargo Space: A 3ft cargo space is preferred over a 2ft cargo space.</li>
<li>Lower Price: Lower prices are preferred.</li>
</ul></li>
<li><p><strong>Less Preferred Features</strong>:</p>
<ul>
<li>Number of Seats: Both 7-seat and 8-seat options are less preferred compared to 6-seat options, with 7-seat options being the least preferred.</li>
<li>Engine Type: Hybrid engines are less preferred, and electric engines are significantly less preferred compared to gas engines.</li>
</ul></li>
</ul>
<p>Based on the results of the MNL model, we can interpret the price coefficient as a dollar-per-util conversion factor, and we can calculate the dollar value of 3ft of cargo space as compared to 2ft of cargo space.</p>
<div id="4a5ab909" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients as a dictionary and access the nested dictionary</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>coefficients <span class="op">=</span> result.params.to_dict()[<span class="dv">0</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar value of 3ft of cargo space compared to 2ft of cargo space</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>dollar_value_cargo_3ft <span class="op">=</span> (coefficients[<span class="st">'cargo_3ft'</span>] <span class="op">/</span> <span class="bu">abs</span>(coefficients[<span class="st">'price'</span>])) <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>dollar_value_cargo_3ft </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>2755.80231518067</code></pre>
</div>
</div>
<p>The dollar value of having 3ft of cargo space compared to 2ft of cargo space is approximately $2,755.80.</p>
<p>This means that respondents value the additional cargo space (3ft vs.&nbsp;2ft) at around $2,755.80, based on their preferences as reflected in the model.</p>
</section>
<section id="predict-market-shares" class="level4">
<h4 class="anchored" data-anchor-id="predict-market-shares">Predict Market Shares</h4>
<p>Assume the market consists of the following 6 minivans. Let’s predict the market shares of each minivan in the market.</p>
<table class="table">
<thead>
<tr class="header">
<th>Minivan</th>
<th>Seats</th>
<th>Cargo</th>
<th>Engine</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>30</td>
</tr>
<tr class="even">
<td>B</td>
<td>6</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="odd">
<td>C</td>
<td>8</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="even">
<td>D</td>
<td>7</td>
<td>3</td>
<td>Gas</td>
<td>40</td>
</tr>
<tr class="odd">
<td>E</td>
<td>6</td>
<td>2</td>
<td>Elec</td>
<td>40</td>
</tr>
<tr class="even">
<td>F</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>35</td>
</tr>
</tbody>
</table>
<div id="98bdfaaf" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define minivan attributes</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>minivan_models <span class="op">=</span> [</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'A'</span>, <span class="st">'seat'</span>: <span class="dv">7</span>, <span class="st">'cargo'</span>: <span class="dv">2</span>, <span class="st">'engine'</span>: <span class="st">'Hyb'</span>, <span class="st">'price'</span>: <span class="dv">30</span>, <span class="st">'seat_7'</span>: <span class="dv">1</span>, <span class="st">'seat_8'</span>: <span class="dv">0</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">0</span>, <span class="st">'eng_hyb'</span>: <span class="dv">1</span>, <span class="st">'eng_elec'</span>: <span class="dv">0</span>},</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'B'</span>, <span class="st">'seat'</span>: <span class="dv">6</span>, <span class="st">'cargo'</span>: <span class="dv">2</span>, <span class="st">'engine'</span>: <span class="st">'Gas'</span>, <span class="st">'price'</span>: <span class="dv">30</span>, <span class="st">'seat_7'</span>: <span class="dv">0</span>, <span class="st">'seat_8'</span>: <span class="dv">0</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">0</span>, <span class="st">'eng_hyb'</span>: <span class="dv">0</span>, <span class="st">'eng_elec'</span>: <span class="dv">0</span>},</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'C'</span>, <span class="st">'seat'</span>: <span class="dv">8</span>, <span class="st">'cargo'</span>: <span class="dv">2</span>, <span class="st">'engine'</span>: <span class="st">'Gas'</span>, <span class="st">'price'</span>: <span class="dv">30</span>, <span class="st">'seat_7'</span>: <span class="dv">0</span>, <span class="st">'seat_8'</span>: <span class="dv">1</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">0</span>, <span class="st">'eng_hyb'</span>: <span class="dv">0</span>, <span class="st">'eng_elec'</span>: <span class="dv">0</span>},</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'D'</span>, <span class="st">'seat'</span>: <span class="dv">7</span>, <span class="st">'cargo'</span>: <span class="dv">3</span>, <span class="st">'engine'</span>: <span class="st">'Gas'</span>, <span class="st">'price'</span>: <span class="dv">40</span>, <span class="st">'seat_7'</span>: <span class="dv">1</span>, <span class="st">'seat_8'</span>: <span class="dv">0</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">1</span>, <span class="st">'eng_hyb'</span>: <span class="dv">0</span>, <span class="st">'eng_elec'</span>: <span class="dv">0</span>},</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'E'</span>, <span class="st">'seat'</span>: <span class="dv">6</span>, <span class="st">'cargo'</span>: <span class="dv">2</span>, <span class="st">'engine'</span>: <span class="st">'Elec'</span>, <span class="st">'price'</span>: <span class="dv">40</span>, <span class="st">'seat_7'</span>: <span class="dv">0</span>, <span class="st">'seat_8'</span>: <span class="dv">0</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">0</span>, <span class="st">'eng_hyb'</span>: <span class="dv">0</span>, <span class="st">'eng_elec'</span>: <span class="dv">1</span>},</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'name'</span>: <span class="st">'F'</span>, <span class="st">'seat'</span>: <span class="dv">7</span>, <span class="st">'cargo'</span>: <span class="dv">2</span>, <span class="st">'engine'</span>: <span class="st">'Hyb'</span>, <span class="st">'price'</span>: <span class="dv">35</span>, <span class="st">'seat_7'</span>: <span class="dv">1</span>, <span class="st">'seat_8'</span>: <span class="dv">0</span>, <span class="st">'cargo_3ft'</span>: <span class="dv">0</span>, <span class="st">'eng_hyb'</span>: <span class="dv">1</span>, <span class="st">'eng_elec'</span>: <span class="dv">0</span>}</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the utility for each minivan</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_utility(minivan, coeffs):</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">=</span> coeffs[<span class="st">'const'</span>]</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'seat_7'</span>] <span class="op">*</span> minivan[<span class="st">'seat_7'</span>]</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'seat_8'</span>] <span class="op">*</span> minivan[<span class="st">'seat_8'</span>]</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'cargo_3ft'</span>] <span class="op">*</span> minivan[<span class="st">'cargo_3ft'</span>]</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'eng_hyb'</span>] <span class="op">*</span> minivan[<span class="st">'eng_hyb'</span>]</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'eng_elec'</span>] <span class="op">*</span> minivan[<span class="st">'eng_elec'</span>]</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    utility <span class="op">+=</span> coeffs[<span class="st">'price'</span>] <span class="op">*</span> minivan[<span class="st">'price'</span>]</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> utility</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate utilities</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>utilities <span class="op">=</span> [calculate_utility(minivan, coefficients) <span class="cf">for</span> minivan <span class="kw">in</span> minivan_models]</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate probabilities using the softmax function</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>exp_utilities <span class="op">=</span> np.exp(utilities)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>market_shares <span class="op">=</span> exp_utilities <span class="op">/</span> np.<span class="bu">sum</span>(exp_utilities)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine results with minivan attributes into a DataFrame</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> minivan, share <span class="kw">in</span> <span class="bu">zip</span>(minivan_models, market_shares):</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>    minivan[<span class="st">'market_share'</span>] <span class="op">=</span> share</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to DataFrame</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>market_share_df <span class="op">=</span> pd.DataFrame(minivan_models)</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Select relevant columns to display</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>market_share_df <span class="op">=</span> market_share_df[[<span class="st">'name'</span>, <span class="st">'seat'</span>, <span class="st">'cargo'</span>, <span class="st">'engine'</span>, <span class="st">'price'</span>, <span class="st">'market_share'</span>]]</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>market_share_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">seat</th>
<th data-quarto-table-cell-role="th">cargo</th>
<th data-quarto-table-cell-role="th">engine</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">market_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>A</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>30</td>
<td>0.116080</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B</td>
<td>6</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
<td>0.419692</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>C</td>
<td>8</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
<td>0.313073</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>D</td>
<td>7</td>
<td>3</td>
<td>Gas</td>
<td>40</td>
<td>0.078412</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>E</td>
<td>6</td>
<td>2</td>
<td>Elec</td>
<td>40</td>
<td>0.020359</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>F</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>35</td>
<td>0.052385</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="interpretation-2" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-2">Interpretation:</h4>
<ol type="1">
<li><strong>Minivan B</strong> has the highest predicted market share at 41.97%. This suggests that the basic configuration with a gas engine and lower price is most preferred.</li>
<li><strong>Minivan C</strong> follows with a market share of 31.31%, indicating a significant preference for larger seating capacity despite the same cargo space and engine type.</li>
<li><strong>Minivan A</strong> has a lower market share of 11.61%, reflecting a lower preference for hybrid engines compared to gas engines.</li>
<li><strong>Minivan D</strong> has a market share of 7.84%, indicating that the preference for additional cargo space is outweighed by the higher price.</li>
<li><strong>Minivan F</strong> has a market share of 5.24%, which is less preferred compared to Minivan A due to the higher price.</li>
<li><strong>Minivan E</strong> has the lowest market share of 2.04%, reflecting a significant aversion to electric engines combined with the higher price.</li>
</ol>
<p>These results provide insights into consumer preferences, highlighting the importance of lower prices and gas engines over hybrid or electric engines and the preference for standard configurations over premium features.</p>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>The conjoint analysis of minivan preferences has provided valuable insights into consumer choices and preferences for different minivan attributes. By estimating a Multinomial Logit (MNL) model using survey data, we determined the relative importance of attributes such as the number of seats, cargo space, engine type, and price.</p>
<section id="key-findings" class="level4">
<h4 class="anchored" data-anchor-id="key-findings">Key Findings:</h4>
<ul>
<li><strong>Price Sensitivity</strong>: Higher prices significantly reduce the likelihood of a minivan being chosen, indicating strong price sensitivity among consumers.</li>
<li><strong>Cargo Space Preference</strong>: Consumers show a clear preference for larger cargo space (3ft over 2ft), highlighting the importance of storage capacity.</li>
<li><strong>Engine Type</strong>: Gas engines are preferred over hybrid and electric engines, with electric engines being the least favored.</li>
<li><strong>Seating Configuration</strong>: The 6-seat configuration is the most preferred, with 7-seat and 8-seat options being less favored. This could be due to perceived or actual benefits in space utilization and comfort in smaller seating configurations.</li>
</ul>
</section>
<section id="market-share-predictions" class="level4">
<h4 class="anchored" data-anchor-id="market-share-predictions">Market Share Predictions:</h4>
<p>The analysis also predicted the market shares for six hypothetical minivan models with varying configurations. The model with a gas engine, 6 seats, and lower price emerged as the most preferred, indicating a potential market advantage for minivans that balance affordability and essential features.</p>
<p>Overall, the Multinomial Logit (MNL) model has proven to be a robust tool for understanding and quantifying consumer preferences, providing automakers with actionable insights to design and market minivans that better align with consumer desires, thereby enhancing market competitiveness and consumer satisfaction.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>